### PR TITLE
doi infrastructure

### PR DESCRIPTION
**Pull request by jukent**
Thank you for your Cookbook contribution!

This PR follows the steps from this [Google Doc on adding DOIs](https://docs.google.com/document/d/1vXXMqiDhB6f3j5TemSp9HouMglXlexdwN6KZCisFkRY/edit). (You had already done some of these steps though, hooray!)

Link checks will fail on Zenodo badges until first release.

Please add or comment affiliations, ORCIDs, or github usernames for the authors of this book (this is optional).

### CODE REVIEW

**Comment by chiaweh2** [comment]
@jukent Thank you so much for the help on this! The link check failed on the zenodo doi. I assume that is due to I have not do the switch and have not release yet for the repo?

**Comment by jukent** [comment]
On Zenodo the repository has been "switched on" or activated. But until there is a release the Zenodo badges will fail.

**Comment by chiaweh2** [comment]
@jukent sorry! I did not notice the PR posted text and go right into the code change.... Thank you for explanation it again!

**Comment by chiaweh2** [comment]
@jukent I also notice I have the switch for the cookbook. Should I also switch it on? or leave it as it is?

**Pull request merged**
